[package]
name = "pyo3-build-config"
version = "0.29.2"
description = "Build configuration for the PyO3 ecosystem"
authors.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
target-lexicon = "0.13.3"

[features]
default = []

# deprecated
resolve-config = []
extension-module = []
generate-import-lib = []
