from _typeshed import Incomplete
from collections.abc import Sequence
from os import PathLike
from typing import Final, final

CONST: Final = 0

@final
class MyClass(dict):
    def __eq__(self, /, other: MyClass) -> bool: ...
    def __ge__(self, /, other: MyClass) -> bool: ...
    def __gt__(self, /, other: MyClass) -> bool: ...
    def __le__(self, /, other: MyClass) -> bool: ...
    def __lt__(self, /, other: MyClass) -> bool: ...
    def __ne__(self, /, other: MyClass) -> bool: ...
    def __new__(cls, /, value: int) -> MyClass: ...
    @classmethod
    @property
    def class_attr(cls, /) -> float: ...
    @classmethod
    def class_method(cls, /) -> str: ...
    @staticmethod
    def static_method() -> bool: ...
    @property
    def value(self, /) -> int: ...
    @value.deleter
    def value(self, /) -> None: ...
    @value.setter
    def value(self, /, value: int) -> None: ...

def some_fn(
    _arg1: tuple[int, Sequence[str | PathLike], dict[str, int]],
    /,
    _arg2: "int",
    *_args,
    _foo: str | None = None,
    **_kwargs,
) -> None: ...
def __getattr__(name: str) -> Incomplete: ...
