[build-system]
# requires = ["maturin @ git+https://github.com/davidhewitt/maturin.git@7a3237299e6bb617f8d4b0957ce205da0f0770d4"]
requires = ["maturin @ git+https://github.com/davidhewitt/maturin.git@88124706b012328041ae8744789340bb9cc95457"]
build-backend = "maturin"
