# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # main cargo workspace does not include `pyo3-benches` and `pyo3-ffi-check`
  # as they are not published to crates.io and occasionally depend on
  # compiler functionality newer than MSRV.

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "cargo"
    directory: "/pyo3-benches/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "cargo"
    directory: "/pyo3-ffi-check/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    labels:
      # dependabot default labels
      - "dependencies"
      - "github-actions"
      # additional labels
      - "CI-skip-changelog"


  # uv & npm used for development tools (locally and in CI)

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 7
    groups:
      uv-tools:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "CI-skip-changelog"

  - package-ecosystem: "npm"
    directory: "/.github/tools/netlify"
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 7
    groups:
      npm-netlify-cli:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "CI-skip-changelog"
