language: python

dist: xenial

cache:
  pip: true
  cargo: true

matrix:
  include:
    - name: Python 2.7
      python: "2.7"
      env: FEATURES=python2
    - name: Python 3.5
      python: "3.5"
      env: FEATURES=python3
    - name: Python 3.6
      python: "3.6"
      env: FEATURES=python3
    - name: Python 3.7
      python: "3.7"
      env: FEATURES=python3
    - name: Python 3.8-dev
      python: "3.8-dev"
      env: FEATURES=python3
    - name: Minimum nightly
      python: "3.7"
      # Keep this synced up with build.rs
      env: FEATURES=python3 TRAVIS_RUST_VERSION=nightly-2019-02-07
    - name: PyPy2.7 6.0
      python: "pypy2.7-6.0"
      env: FEATURES=python2
    - name: PyPy3.5 6.0
      python: "pypy3.5-6.0"
      env: FEATURES=python3
  allow_failures:
    - python: "3.8-dev"
      env: FEATURES=python3
    - python: pypy3.5-6.0
      env: FEATURES=python3

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_install:
  - source ./ci/travis/setup.sh

install:
  - pip install setuptools-rust pytest pytest-benchmark tox

script:
  - ./ci/travis/test.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./ci/travis/guide.sh
    on:
      branch: master
      repo: PyO3/pyo3
      python: 3.6
      condition: $TRAVIS_EVENT_TYPE != "cron"
  - provider: script
    skip_cleanup: true
    script: ./ci/travis/guide.sh
    on:
      tags: true
      repo: PyO3/pyo3
      python: 3.6

notifications:
  email: false
