sudo: required
dist: trusty
language: python

cache:
  pip: true
  directories:
  - "$HOME/.cargo"
  - "$HOME/kcov"

matrix:
  include:
  - python: "2.7"
    env: FEATURES=python2
  - python: "3.5"
    env: FEATURES=python3
  - python: "3.6"
    env: FEATURES=python3
  - python: "3.7-dev"
    env: FEATURES=python3
  allow_failures:
  - python: "3.7-dev"
    env: FEATURES=python3

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUSTFLAGS="-C link-dead-code"
    - RUST_BACKTRACE=1
    - SCCACHE_DIR="$HOME/.cargo/sccache"
    - RUSTC_WRAPPER=sccache

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_install:
  - source ./ci/travis/setup.sh

install:
  - pip install setuptools-rust pytest pytest-benchmark

script:
  - source ./ci/travis/test.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./ci/travis/cover.sh
    on:
      branch: master


# after_success:
#   - source ./ci/travis/cover.sh
# - make clippy

# after_success:
#   - |
#     if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
#     cargo doc --no-deps &&
#     echo "<meta http-equiv=refresh content=0;url=os_balloon/index.html>" > target/doc/index.html &&
#     curl -sL https://github.com/rust-lang-nursery/mdBook/releases/download/v0.1.5/mdbook-v0.1.5-x86_64-unknown-linux-gnu.tar.gz | tar xvz -C $HOME/rust/bin &&
#     cd guide && mdbook build -d ../target/doc/guide && cd .. &&
#     git clone https://github.com/davisp/ghp-import.git &&
#     ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
#     echo "Uploaded documentation"
#     fi
#
