[[disallowed-types]]
path = "std::sync::Mutex"
reason = "use crate::platform::sync::non_poison::Mutex for `no_std` compatibility"

[[disallowed-types]]
path = "std::sync::Once"
reason = "use crate::platform::sync::Once for no_std compatibility"
