[[disallowed-types]]
path = "std::hash::DefaultHasher"
reason = "use crate::platform::DefaultHashBuilder instead"

[[disallowed-types]]
path = "core::hash::BuildHasherDefault"
reason = "use crate::platform::DefaultHashBuilder instead"
