name: 'Prepare coverage'
description: 'Installs cargo-llvm-cov and prepares the environment for coverage collection'
inputs:
  host_only:
    description: 'Whether to prepare the environment for host-only coverage collection'
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
  - name: Install cargo-llvm-cov
    uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6 # v2.82.6

  - name: Prepare coverage environment
    shell: bash
    run: |
      cargo llvm-cov clean --workspace
      uvx nox -s set-coverage-env -- ${{ inputs.host_only == 'true' && '--coverage-host-only' || '' }}
    env:
      CARGO_LLVM_COV_SETUP: "yes"
