name: 'Prepare coverage'
description: 'Installs cargo-llvm-cov and prepares the environment for coverage collection'
inputs:
  host_only:
    description: 'Whether to prepare the environment for host-only coverage collection'
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
  - name: Install cargo-llvm-cov
    uses: taiki-e/install-action@4cef1412cce204788f482e778a0b9187f9626a29 # v2.87.21
    with:
      tool: cargo-llvm-cov

  - name: Prepare coverage environment
    shell: bash
    run: |
      cargo llvm-cov clean --workspace
      uv run --isolated --only-group nox nox -s set-coverage-env -- ${{ inputs.host_only == 'true' && '--coverage-host-only' || '' }}
    env:
      CARGO_LLVM_COV_SETUP: "yes"
