[package]
name = "pyo3-ffi-check-macro"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
glob = "0.3"
quote = "1"
proc-macro2 = "1.0.60"
scraper = "0.17"
pyo3-build-config = { path = "../../pyo3-build-config" }
