from typing import Any, final

@final
class FutureAwaitable:
    def __await__(self, /) -> FutureAwaitable: ...
    def __iter__(self, /) -> FutureAwaitable: ...
    def __new__(cls, /, result: Any) -> FutureAwaitable: ...
    def __next__(self, /) -> FutureAwaitable: ...
    @property
    def _asyncio_future_blocking(self, /) -> bool: ...
    @_asyncio_future_blocking.setter
    def _asyncio_future_blocking(self, /, value: bool) -> None: ...

@final
class IterAwaitable:
    def __await__(self, /) -> IterAwaitable: ...
    def __iter__(self, /) -> IterAwaitable: ...
    def __new__(cls, /, result: Any) -> IterAwaitable: ...
    def __next__(self, /) -> Any: ...
