from typing import Any, final

@final
class FutureAwaitable:
    def __await__(self, /) -> FutureAwaitable: ...
    def __iter__(self, /) -> FutureAwaitable: ...
    def __new__(cls, /, result: Any) -> FutureAwaitable: ...
    def __next__(self, /) -> FutureAwaitable: ...
    @property
    def _asyncio_future_blocking(self, /) -> bool: ...
    @_asyncio_future_blocking.setter
    def _asyncio_future_blocking(self, /, value: bool) -> None: ...
    def close(self, /) -> None: ...
    def send(self, /, _value: Any) -> FutureAwaitable: ...
    def throw(
        self, /, _value: Any, _a: Any | None = None, _b: Any | None = None
    ) -> FutureAwaitable: ...

@final
class IterAwaitable:
    def __await__(self, /) -> IterAwaitable: ...
    def __iter__(self, /) -> IterAwaitable: ...
    def __new__(cls, /, result: Any) -> IterAwaitable: ...
    def __next__(self, /) -> Any: ...
    def close(self, /) -> None: ...
    def send(self, /, value: Any) -> Any: ...
    def throw(
        self, /, value: Any, _a: Any | None = None, _b: Any | None = None
    ) -> Any: ...
