from typing import SupportsIndex, final

@final
class Eq:
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: SupportsIndex) -> Eq: ...

@final
class EqDefaultNe:
    def __eq__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: SupportsIndex) -> EqDefaultNe: ...

@final
class EqDerived:
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, value: SupportsIndex) -> EqDerived: ...

@final
class Ordered:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: SupportsIndex) -> Ordered: ...

@final
class OrderedDefaultNe:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: SupportsIndex) -> OrderedDefaultNe: ...

@final
class OrderedDerived:
    def __eq__(self, value: object, /) -> bool: ...
    def __ge__(self, value: object, /) -> bool: ...
    def __gt__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, value: object, /) -> bool: ...
    def __lt__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, value: SupportsIndex) -> OrderedDerived: ...
    def __str__(self, /) -> str: ...

@final
class OrderedRichCmp:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: SupportsIndex) -> OrderedRichCmp: ...
