class ComplexEnum: ...
class MixedComplexEnum: ...

class SimpleEnum:
    def __eq__(self, /, other: SimpleEnum | int) -> bool: ...
    def __ne__(self, /, other: SimpleEnum | int) -> bool: ...

class SimpleTupleEnum: ...
class TupleEnum: ...

def do_complex_stuff(thing: ComplexEnum) -> ComplexEnum: ...
def do_mixed_complex_stuff(thing: MixedComplexEnum) -> MixedComplexEnum: ...
def do_simple_stuff(thing: SimpleEnum) -> SimpleEnum: ...
def do_tuple_stuff(thing: TupleEnum) -> TupleEnum: ...
