from typing import final

class ComplexEnum:
    @final
    class EmptyStruct(ComplexEnum): ...

    @final
    class Float(ComplexEnum): ...

    @final
    class Int(ComplexEnum): ...

    @final
    class MultiFieldStruct(ComplexEnum): ...

    @final
    class Str(ComplexEnum): ...

    @final
    class VariantWithDefault(ComplexEnum): ...

class MixedComplexEnum:
    @final
    class Empty(MixedComplexEnum): ...

    @final
    class Nothing(MixedComplexEnum): ...

@final
class SimpleEnum:
    def __eq__(self, /, other: SimpleEnum | int) -> bool: ...
    def __ne__(self, /, other: SimpleEnum | int) -> bool: ...

class SimpleTupleEnum:
    @final
    class Int(SimpleTupleEnum): ...

    @final
    class Str(SimpleTupleEnum): ...

class TupleEnum:
    @final
    class EmptyTuple(TupleEnum): ...

    @final
    class Full(TupleEnum): ...

    @final
    class FullWithDefault(TupleEnum): ...

def do_complex_stuff(thing: ComplexEnum) -> ComplexEnum: ...
def do_mixed_complex_stuff(thing: MixedComplexEnum) -> MixedComplexEnum: ...
def do_simple_stuff(thing: SimpleEnum) -> SimpleEnum: ...
def do_tuple_stuff(thing: TupleEnum) -> TupleEnum: ...
