class MyValueError(ValueError): ...

def raise_my_value_error() -> None: ...
def return_my_value_error() -> MyValueError: ...
def return_pyerr() -> BaseException: ...
def return_value_error() -> ValueError: ...
