from _typeshed import Incomplete
from typing import Any

def raise_my_value_error() -> None: ...
def return_my_value_error() -> Any: ...
def return_pyerr() -> BaseException: ...
def return_value_error() -> ValueError: ...
def __getattr__(name: str) -> Incomplete: ...
