from typing import Any, final

@final
class DelDropProbe:
    def __del__(self, /) -> None: ...
    def __new__(cls, /) -> DelDropProbe: ...

def accepts_bool(val: bool) -> bool: ...
def del_drop_counts() -> tuple[int, int]: ...
def detach_during_finalization() -> Any: ...
def get_item_and_run_callback(dict: dict, callback: Any) -> None: ...
def get_type_fully_qualified_name(obj: Any) -> str: ...
def hammer_attaching_in_thread() -> Any: ...
def issue_219() -> None: ...
def reset_del_drop_counts() -> None: ...
