from _typeshed import Incomplete

def identity_bits(b: Incomplete) -> Incomplete: ...
def identity_color(c: Incomplete) -> Incomplete: ...
def identity_permission(p: Incomplete) -> Incomplete: ...
def identity_status(s: Incomplete) -> Incomplete: ...
def __getattr__(name: str) -> Incomplete: ...
