from os import PathLike
from pathlib import Path

__all__ = ["make_path", "take_name_or_path", "take_pathbuf"]

def make_path() -> Path: ...
def take_name_or_path(value: str | PathLike[str]) -> Path: ...
def take_pathbuf(path: str | PathLike[str]) -> Path: ...
