import typing

def args_kwargs(*args, **kwargs) -> typing.Any: ...
def none() -> None: ...
def positional_only(a: typing.Any, /, b: typing.Any) -> typing.Any: ...
def simple(
    a: typing.Any, b: typing.Any | None = None, *, c: typing.Any | None = None
) -> typing.Any: ...
def simple_args(
    a: typing.Any, b: typing.Any | None = None, *args, c: typing.Any | None = None
) -> typing.Any: ...
def simple_args_kwargs(
    a: typing.Any,
    b: typing.Any | None = None,
    *args,
    c: typing.Any | None = None,
    **kwargs,
) -> typing.Any: ...
def simple_kwargs(
    a: typing.Any, b: typing.Any | None = None, c: typing.Any | None = None, **kwargs
) -> typing.Any: ...
def with_typed_args(
    a: bool = False, b: int = 0, c: float = 0.0, d: str = ""
) -> typing.Any: ...
