import typing

def args_kwargs(*args, **kwargs): ...
def none(): ...
def positional_only(a: typing.Any, /, b: typing.Any): ...
def simple(
    a: typing.Any, b: typing.Any | None = None, *, c: typing.Any | None = None
): ...
def simple_args(
    a: typing.Any, b: typing.Any | None = None, *args, c: typing.Any | None = None
): ...
def simple_args_kwargs(
    a: typing.Any,
    b: typing.Any | None = None,
    *args,
    c: typing.Any | None = None,
    **kwargs,
): ...
def simple_kwargs(
    a: typing.Any, b: typing.Any | None = None, c: typing.Any | None = None, **kwargs
): ...
def with_typed_args(a: bool = False, b: int = 0, c: float = 0.0, d: str = ""): ...
