from collections.abc import Sequence

def array_to_array_i32(arr: Sequence[int]) -> list[int]: ...
def vec_to_vec_i32(vec: Sequence[int]) -> list[int]: ...
def vec_to_vec_pystring(vec: Sequence[str]) -> list[str]: ...
