from _typeshed import SupportsGetItem, SupportsLenAndGetItem
from typing import SupportsIndex

__all__ = ["array_to_array_i32", "vec_to_vec_i32", "vec_to_vec_pystring"]

def array_to_array_i32(arr: SupportsLenAndGetItem[SupportsIndex]) -> list[int]: ...
def vec_to_vec_i32(vec: SupportsGetItem[int, SupportsIndex]) -> list[int]: ...
def vec_to_vec_pystring(vec: SupportsGetItem[int, str]) -> list[str]: ...
