from collections.abc import Sequence
from typing import SupportsIndex

def array_to_array_i32(arr: Sequence[SupportsIndex]) -> list[int]: ...
def vec_to_vec_i32(vec: Sequence[SupportsIndex]) -> list[int]: ...
def vec_to_vec_pystring(vec: Sequence[str]) -> list[str]: ...
