from typing import final

@final
class SubDict(dict):
    def __new__(cls, /) -> SubDict: ...
    def __str__(self, /) -> str: ...

@final
class Subclass(Subclassable):
    def __new__(cls, /) -> Subclass: ...
    def __str__(self, /) -> str: ...

class Subclassable:
    def __new__(cls, /) -> Subclassable: ...
    def __str__(self, /) -> str: ...
