from typing import Self, final
from typing_extensions import disjoint_base

@final
class SubDict(dict):
    def __new__(cls, /) -> Self: ...
    def __str__(self, /) -> str: ...

@final
class Subclass(Subclassable):
    def __new__(cls, /) -> Self: ...
    def __str__(self, /) -> str: ...

@disjoint_base
class Subclassable:
    def __new__(cls, /) -> Self: ...
    def __str__(self, /) -> str: ...
