[package]
name = "sequential"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[lib]
name = "sequential"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3-ffi = { path = "../../", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = { path = "../../../pyo3-build-config" }

[workspace]
