name: benches

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}-benches
  cancel-in-progress: true

env:
  UV_CONSTRAINT: ${{ github.workspace }}/.github/uv-constraints.txt
  UV_PYTHON: "3.14t"

permissions:
  contents: read

jobs:
  benchmarks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          save-cache: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'CI-save-pr-cache') }}

      # Using this action is still necessary for CodSpeed to build flamegraphs correctly,
      # see note about setup-python in https://codspeed.io/docs/benchmarks/python#recipes
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: ${{ env.UV_PYTHON }}

      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          components: rust-src

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          workspaces: |
            .
            pyo3-benches
          save-if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'CI-save-pr-cache') }}
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - uses: taiki-e/install-action@76c2e6406e52637deed7160d77bded76bd83e06e # v2
        with:
          tool: cargo-codspeed

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@373d6868929f444bc08d901fd0eb0ad52a8875ea # v5.2.1
        with:
          run: uvx nox -s codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: simulation
