name: changelog

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, edited]

env:
  UV_PYTHON: "3.14"
  NOX_DEFAULT_VENV_BACKEND: uv

permissions: {}

jobs:
  check:
    name: Check changelog entry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Install uv"
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: ${{ github.event_name == 'pull_request' }}

      - run: uvx nox -s check-changelog
