name: changelog

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, edited]

jobs:
  check:
    name: Check changelog entry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@v7
      - run: uvx nox -s check-changelog
