name: Sync Translations on Doc Changes

on:
  push:
    branches: [main]
    paths:
      - 'guide/**/*.md'  # 监控guide下所有.md变化

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 获取前一个commit以便diff

      - name: Find changed English docs
        id: changes
        run: |
          # git diff找出变化的文件，排除zh-CN
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- guide/**/*.md | grep -v '/zh-CN/' || true)
          if [ -n "$CHANGED_FILES" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue for translation update
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-issue-from-file@v5  # 这个action创建Issue，更灵活（GitHub会自动安装）
        with:
          title: "英文文档更新：需要同步中文翻译"
          content: |
            以下英文文件有变化，请检查并更新对应中文版本（在guide/zh-CN/下）：
            
            ${{ steps.changes.outputs.files }}