# This runs as a separate job because it needs to run on the `workflow_run` event
# in order to access the netlify secrets.
#
# This is safe because this doesn't run arbitrary code from PRs.

name: netlify-deploy

on:
  workflow_run:
    workflows: ["netlify-build"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    environment: netlify

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Install netlify-cli
        run: |
          npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          ls -la
          DEBUG=* netlify deploy \
              --site ${{ secrets.NETLIFY_SITE_ID }} \
              --auth ${{ secrets.NETLIFY_TOKEN }} \
              ${{ github.event.workflow_run.head_branch == 'main' && '--prod' || '' }}
