name: Release Rust Crate

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: The version to build

env:
  UV_CONSTRAINT: ${{ github.workspace }}/.github/uv-constraints.txt

jobs:
  release:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # The tag to build or the tag received by the tag event
          ref: ${{ github.event.inputs.version || github.ref }}
          persist-credentials: false

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: false

      - uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5
        id: auth

      - name: Publish to crates.io
        run: cargo publish --workspace
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
